#!/usr/bin/python3

def raise_exception():
    raise TypeError('This exception was raised intentionally')




if __name__=='__main__':
    raise_exception_msg()

